[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/auth/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
