[build]
builder = "dockerfile"
# No buildCommand needed when using Dockerfile

[deploy]
startCommand = "node server.js"
healthcheckPath = "/auth/health"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"
