[build]
builder = "nixpacks"
providers = ["nodejs"]
buildCommand = "npm install --production=false"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/auth/health"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"
